let passwords = [
    {
        id:1,
        username:"nurillo",
        firstname:"Nurillo",
        lastname:"Suyunboyev",
        password:"123"
    },
    {
        id:2,
        username:"ulug'bek",
        firstname:"Ulug'bek",
        lastname:"Rahmatillayev",
        password:"123"
    },
    {
        id:3,
        username:"shamsiddin",
        firstname:"Shamsiddin",
        lastname:"Boyqulov",
        password:"123"
    },
    {
        id:4,
        username:"mirzo",
        firstname:"Mirzo",
        lastname:"Suyunboyev",
        password:"123"
    },
    {
        id:5,
        username:"sarvar",
        firstname:"Sarvar",
        lastname:"A'zamov",
        password:"123"
    },
    {
        id:6,
        username:"ozodbek",
        firstname:"Nurillo",
        lastname:"Suyunboyev",
        password:"123"
    },
    {
        id:7,
        username:"nigora",
        firstname:"Nigora",
        lastname:"Xasanova",
        password:"123"
    },
    {
        id:8,
        username:"laylo",
        firstname:"Laylo",
        lastname:"Ismatullayeva",
        password:"123"
    },
    {
        id:9,
        username:"muslima",
        firstname:"Muslima",
        lastname:"Yoqubova",
        password:"123"
    },
    {
        id:10,
        username:"dilnoza",
        firstname:"Dilnoza",
        lastname:"Raxmatullaeva",
        password:"123"
    },
    {
        id:11,
        username:"roziya",
        firstname:"Roziya",
        lastname:"G'ayratullayeva",
        password:"123"
    },
    {
        id:12,
        username:"hamroz",
        firstname:"Hamroz",
        lastname:"Nuriddinov",
        password:"123"
    },
    {
        id:13,
        username:"ibrohim",
        firstname:"Ibrohim",
        lastname:"Shukurullayev",
        password:"123"
    },
    {
        id:14,
        username:"abduvohob",
        firstname:"Abduvahob",
        lastname:"Mirzaahmedov",
        password:"123"
    },
    {
        id:15,
        username:"abdulla",
        firstname:"Abdulla",
        lastname:"Sultonmurodov",
        password:"123"
    },
    {
        id:16,
        username:"muhammadali",
        firstname:"Muhammadali",
        lastname:"Rustambekov",
        password:"123"
    },
     {
        id:17,
        username:"jamshidbek",
        firstname:"Jamshidbek",
        lastname:"Akramov",
        password:"123"
    }
]

